name: Validation

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validation:
    name: Validation on ${{ matrix.os }} @ ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ['14', '16', '18', '20', '22']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node }}
      - name: npm ci
        run: npm ci
      - name: npm run lint
        run: npm run lint
      - name: npm test
        run: npm test
